# Generated by Django 5.2.4 on 2025-07-26 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("team_invitation", "Team Invitation"),
                            ("project_update", "Project Update"),
                            ("system_message", "System Message"),
                            ("welcome", "Welcome Message"),
                        ],
                        default="system_message",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "related_project_id",
                    models.UUIDField(
                        blank=True, help_text="ID of related project", null=True
                    ),
                ),
                (
                    "related_user_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of related user (e.g., who sent invitation)",
                        null=True,
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True, help_text="URL for action button", max_length=500
                    ),
                ),
                (
                    "action_text",
                    models.CharField(
                        blank=True, help_text="Text for action button", max_length=100
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When notification expires", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="authenticat_user_id_b72bc2_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "created_at"],
                        name="authenticat_notific_8338cc_idx",
                    ),
                    models.Index(
                        fields=["priority", "created_at"],
                        name="authenticat_priorit_3e2e4d_idx",
                    ),
                ],
            },
        ),
    ]
