# Generated by Django 5.2.4 on 2025-07-08 11:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=255)),
                ("record_id", models.CharField(max_length=255)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        max_length=10,
                    ),
                ),
                ("data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("attempts", models.IntegerField(default=0)),
                ("last_attempt", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("syncing", "Syncing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("priority", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sync_queue",
                "ordering": ["-priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="sync_queue_status_44b1b4_idx",
                    ),
                    models.Index(
                        fields=["table_name", "record_id"],
                        name="sync_queue_table_n_8b2910_idx",
                    ),
                    models.Index(
                        fields=["priority", "status"],
                        name="sync_queue_priorit_4b8903_idx",
                    ),
                    models.Index(
                        fields=["created_by", "status"],
                        name="sync_queue_created_c049b5_idx",
                    ),
                ],
            },
        ),
    ]
