# Generated by Django 5.2.3 on 2025-06-19 09:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forms", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("respondent_id", models.CharField(max_length=255)),
                ("response_value", models.TextField()),
                ("metadata", models.JSONField(default=dict)),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
                ("location_data", models.JSONField(blank=True, null=True)),
                ("sync_status", models.CharField(default="pending", max_length=20)),
                (
                    "collected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collected_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="projects.project",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="forms.question",
                    ),
                ),
            ],
            options={
                "ordering": ["-collected_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "question"],
                        name="responses_r_project_34083e_idx",
                    ),
                    models.Index(
                        fields=["respondent_id"], name="responses_r_respond_d74e00_idx"
                    ),
                    models.Index(
                        fields=["collected_by"], name="responses_r_collect_52c6a7_idx"
                    ),
                    models.Index(
                        fields=["collected_at"], name="responses_r_collect_91af7e_idx"
                    ),
                ],
            },
        ),
    ]
