# Generated by Django 5.2.3 on 2025-06-26 21:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0003_rename_question_type_question_response_type"),
        ("projects", "0001_initial"),
        ("responses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Respondent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "respondent_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("demographics", models.JSONField(blank=True, default=dict)),
                ("location_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_response_at", models.DateTimeField(blank=True, null=True)),
                ("is_anonymous", models.BooleanField(default=True)),
                ("consent_given", models.BooleanField(default=False)),
                ("sync_status", models.CharField(default="pending", max_length=20)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="response",
            name="responses_r_respond_d74e00_idx",
        ),
        migrations.RenameField(
            model_name="response",
            old_name="id",
            new_name="response_id",
        ),
        migrations.RenameField(
            model_name="response",
            old_name="metadata",
            new_name="response_metadata",
        ),
        migrations.RemoveField(
            model_name="response",
            name="respondent_id",
        ),
        migrations.AddField(
            model_name="response",
            name="data_quality_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="response",
            name="device_info",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="response",
            name="is_validated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="response",
            name="legacy_respondent_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="response",
            name="synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="response",
            name="validation_errors",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="respondent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_respondents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="respondent",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respondents",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="respondent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="responses.respondent",
            ),
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(
                fields=["respondent"], name="responses_r_respond_d74e00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(
                fields=["sync_status"], name="responses_r_sync_st_535633_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="respondent",
            index=models.Index(
                fields=["project"], name="responses_r_project_ed44d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="respondent",
            index=models.Index(
                fields=["respondent_id"], name="responses_r_respond_b2fb4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="respondent",
            index=models.Index(
                fields=["created_at"], name="responses_r_created_0c031c_idx"
            ),
        ),
    ]
