# Generated by Django 5.2.3 on 2025-06-26 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("responses", "0003_migrate_respondent_data"),
    ]

    operations = [
        # Remove the legacy field
        migrations.RemoveField(
            model_name='response',
            name='legacy_respondent_id',
        ),
        # Make respondent field non-nullable
        migrations.AlterField(
            model_name='response',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='responses.respondent'),
        ),
        # Add unique constraint back
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('question', 'respondent')},
        ),
    ]
