# Generated by Django 5.2.3 on 2025-06-30 16:37

import django.db.models.deletion
import responses.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0003_rename_question_type_question_response_type"),
        ("projects", "0001_initial"),
        ("responses", "0004_cleanup_legacy_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("numeric", "Numeric"),
                            ("boolean", "Boolean"),
                            ("datetime", "Date/Time"),
                            ("json", "JSON/Structured"),
                            ("file", "File/Media"),
                            ("geospatial", "Geographic"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "validation_schema",
                    models.JSONField(
                        default=dict, help_text="JSON schema for validation"
                    ),
                ),
                (
                    "default_constraints",
                    models.JSONField(
                        default=dict, help_text="Default validation rules"
                    ),
                ),
                (
                    "analytics_category",
                    models.CharField(
                        choices=[
                            ("descriptive", "Descriptive Analytics"),
                            ("qualitative", "Qualitative Analytics"),
                            ("inferential", "Inferential Analytics"),
                            ("geospatial", "Geospatial Analytics"),
                            ("temporal", "Temporal Analytics"),
                        ],
                        max_length=50,
                    ),
                ),
                ("input_widget", models.CharField(default="text_input", max_length=50)),
                ("supports_options", models.BooleanField(default=False)),
                ("supports_media", models.BooleanField(default=False)),
                ("supports_geolocation", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.AddField(
            model_name="response",
            name="choice_selections",
            field=models.JSONField(
                default=list, help_text="Selected choices for multiple choice"
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="datetime_value",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="response",
            name="geo_accuracy",
            field=models.FloatField(
                blank=True, help_text="GPS accuracy in meters", null=True
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="geo_data",
            field=models.JSONField(
                blank=True, help_text="Geographic coordinates and shapes", null=True
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="media_files",
            field=models.JSONField(
                default=list, help_text="List of associated media files"
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="numeric_value",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="response_format",
            field=models.JSONField(
                default=dict, help_text="Format specifications, units, etc."
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="structured_data",
            field=models.JSONField(
                default=dict, help_text="Type-specific structured data"
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="response_value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="response",
            name="response_type",
            field=models.ForeignKey(
                default=responses.models.get_default_response_type,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="responses.responsetype",
            ),
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(
                fields=["response_type"], name="responses_r_respons_1b3297_idx"
            ),
        ),
    ]
