# Generated by Django 5.2.3 on 2025-06-19 09:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("numeric", "Numeric"),
                            ("text", "Text"),
                            ("choice", "Multiple Choice"),
                            ("scale", "Scale"),
                            ("date", "Date"),
                            ("location", "Location"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("options", models.JSONField(blank=True, null=True)),
                ("validation_rules", models.JSONField(blank=True, null=True)),
                ("order_index", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sync_status", models.CharField(default="pending", max_length=20)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index", "created_at"],
                "unique_together": {("project", "order_index")},
            },
        ),
    ]
