# Generated by Django 5.2.4 on 2025-08-05 15:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("text_short", "Short Text"),
                            ("text_long", "Long Text"),
                            ("numeric_integer", "Number (Integer)"),
                            ("numeric_decimal", "Number (Decimal)"),
                            ("scale_rating", "Rating Scale"),
                            ("choice_single", "Single Choice"),
                            ("choice_multiple", "Multiple Choice"),
                            ("date", "Date"),
                            ("datetime", "Date & Time"),
                            ("geopoint", "GPS Location"),
                            ("geoshape", "Geographic Shape"),
                            ("image", "Photo/Image"),
                            ("audio", "Audio Recording"),
                            ("video", "Video Recording"),
                            ("file", "File Upload"),
                            ("signature", "Digital Signature"),
                            ("barcode", "Barcode/QR Code"),
                            ("numeric", "Numeric (Legacy)"),
                            ("text", "Text (Legacy)"),
                            ("choice", "Multiple Choice (Legacy)"),
                            ("scale", "Scale (Legacy)"),
                            ("location", "Location (Legacy)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("allow_multiple", models.BooleanField(default=False)),
                ("options", models.JSONField(blank=True, null=True)),
                ("validation_rules", models.JSONField(blank=True, null=True)),
                ("order_index", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sync_status", models.CharField(default="pending", max_length=20)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index", "created_at"],
                "unique_together": {("project", "order_index")},
            },
        ),
    ]
