# Generated by Django 5.2.3 on 2025-06-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="allow_multiple",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("numeric", "Numeric"),
                    ("text", "Text"),
                    ("long_text", "Long Text"),
                    ("choice", "Multiple Choice"),
                    ("scale", "Scale"),
                    ("date", "Date"),
                    ("location", "Location"),
                ],
                max_length=20,
            ),
        ),
    ]
