# Generated by Django 5.2.3 on 2025-06-26 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_question_allow_multiple_alter_question_question_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="question_type",
            new_name="response_type",
        ),
    ]
