# Generated by Django 5.2.3 on 2025-06-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0003_rename_question_type_question_response_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="response_type",
            field=models.CharField(
                choices=[
                    ("text_short", "Short Text"),
                    ("text_long", "Long Text"),
                    ("numeric_integer", "Number (Integer)"),
                    ("numeric_decimal", "Number (Decimal)"),
                    ("scale_rating", "Rating Scale"),
                    ("choice_single", "Single Choice"),
                    ("choice_multiple", "Multiple Choice"),
                    ("date", "Date"),
                    ("datetime", "Date & Time"),
                    ("geopoint", "GPS Location"),
                    ("geoshape", "Geographic Shape"),
                    ("image", "Photo/Image"),
                    ("audio", "Audio Recording"),
                    ("video", "Video Recording"),
                    ("file", "File Upload"),
                    ("signature", "Digital Signature"),
                    ("barcode", "Barcode/QR Code"),
                    ("numeric", "Numeric (Legacy)"),
                    ("text", "Text (Legacy)"),
                    ("choice", "Multiple Choice (Legacy)"),
                    ("scale", "Scale (Legacy)"),
                    ("location", "Location (Legacy)"),
                ],
                max_length=20,
            ),
        ),
    ]
